### ISSUE TITLE
Could use querystring or url modules to parse url??

### ISSUE THREAD

**Issue by haydnba** [fac-13/vithAutocomplete#45]
Obvs we didn't do this either but might be wort a look https://nodejs.org/api/querystring.html

©️

https://github.com/fac-13/vithAutocomplete/blob/1e34116aa8d1b2cf4e35361023a186f42ed54eb4/src/handlers.js#L29-L31

**Comment by i2xzy** [comment]
and add insensitive flag to regex

**Comment by haydnba** [comment]
Oh... seems like you DID do this, in src/logic.js...


🤗🤓🤑

**Comment by helenzhou6** [comment]
Also BUG: e.g. when entering DAVID in all caps
